### ISSUE TITLE
[Feature Request] Player actor tokens linger on previous scene

### ISSUE THREAD

**Issue by Syxereza** [OriginalDecode/elysium-dnd#2]
Placing a player token on another scene pulls the player to that scene, but other players still on the first scene can still see the pulled players token

Player A token is placed on Scene A
Player B token is placed on Scene A

Player A token is placed on Scene B - Player A now see Scene B, instead of Scene A
Player B can still see Player A's "old" token in Scene A

**Comment by linus-skold** [comment]
This should be resolved with [v0.2.2](https://github.com/OriginalDecode/elysium-dnd/releases/tag/v0.2.2) or more specifically with this commit https://github.com/OriginalDecode/elysium-dnd/commit/aa75bcde7d192f219949494fb5625289478503cb

**Comment by Syxereza** [comment]
Resolved in v0.2.2, closing
