### ISSUE TITLE
Combat tokens, auto roll initiative for combat npcs

### ISSUE THREAD

**Issue by linus-skold** [OriginalDecode/elysium-dnd#4]
Automatically roll initiative for combat flagged NPCs on the current scene when anyone rolls initiative.
Players should still roll their own initiative.

**Comment by Syxereza** [comment]
Macro:

/**

* Takes all selected tokens and adds them to the combat tracker. Then rolls initative for all NPC tokens.

*/

async function main() {

await canvas.tokens.toggleCombat();

game.combat.rollNPC({ messageOptions: { rollMode: CONST.DICE_ROLL_MODES.PRIVATE }})

}

main();
