### ISSUE TITLE
On join, pull player to scene where their token is located

### ISSUE THREAD

**Issue by Syxereza** [OriginalDecode/elysium-dnd#6]
Currently when a player joins a game session they're taken to the currently active scene.

It would be a nice QoL change if the player, when joining a game session, is taken to the scene where their token is. Similar to how a player is taken to a scene when their token is placed in that scene.

**Comment by linus-skold** [comment]
Resolved in https://github.com/OriginalDecode/elysium-dnd/pull/7 
Will require Foundry v10 due to the `userConnected` event not being available in v9

**Comment by linus-skold** [comment]
Different solution used using websockets and ready events instead. With release
https://github.com/OriginalDecode/elysium-dnd/releases/tag/v0.4.0
only requires version 9, verified on 10
